name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  workflow_dispatch: # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clonar o repositório
      - name: Clonar o Repositório
        uses: actions/checkout@v3

      # Gerar a cobra (Snake)
      - name: Gerar a Cobra
        uses: Platane/snk@v2
        with:
          github_user_name: silvaluccs # Substitua pelo seu nome de usuário no GitHub
          outputs: dist/snake.svg

      # Publicar no branch output
      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
