name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente
  workflow_dispatch: # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o Repositório
        uses: actions/checkout@v3

      - name: Gerar a Cobra
        uses: Platane/snk@v2
        with:
          github_user_name: silvaluccs # Substitua pelo seu usuário do GitHub
          outputs: dist/snake.svg

      - 
